{{- if .Values.sourcesApi.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cost-management-onprem.fullname" . }}-sources-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-management-onprem.labels" . | nindent 4 }}
type: Opaque
data:
  database-password: {{ .Values.database.sources.password | default "postgres" | b64enc | quote }}
  encryption-key: {{ .Values.sourcesApi.encryptionKey | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cost-management-onprem.fullname" . }}-db-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-management-onprem.labels" . | nindent 4 }}
type: Opaque
data:
  sources-password: {{ .Values.database.sources.password | default "postgres" | b64enc | quote }}
{{- end }}
