apiVersion: v1
kind: Service
metadata:
  name: {{ include "cost-management-onprem.fullname" . }}-sources-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-management-onprem.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
    app.kubernetes.io/name: sources-api
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.sourcesApi.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cost-management-onprem.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
    app.kubernetes.io/name: sources-api