apiVersion: batch/v1
kind: Job
metadata:
  name: db-init
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-mgmt-infra.labels" . | nindent 4 }}
    app.kubernetes.io/component: db-init
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "cost-mgmt-infra.labels" . | nindent 8 }}
        app.kubernetes.io/component: db-init
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "cost-mgmt-infra.serviceAccountName" . }}
      containers:
      - name: db-init
        image: bitnami/kubectl:latest
        command:
        - bash
        - -c
        - |
          set -e

          echo "=== Waiting for PostgreSQL pod to be ready ==="
          kubectl wait --for=condition=ready pod/postgres-0 -n {{ .Release.Namespace }} --timeout=300s

          echo "=== Database Initialization ==="

          # Get database credentials
          KOKU_DB_NAME=$(kubectl get secret {{ include "cost-mgmt-infra.postgresql.secretName" . }} -n {{ .Release.Namespace }} -o jsonpath='{.data.database}' | base64 -d)
          KOKU_DB_USER=$(kubectl get secret {{ include "cost-mgmt-infra.postgresql.secretName" . }} -n {{ .Release.Namespace }} -o jsonpath='{.data.username}' | base64 -d)
          KOKU_DB_PASSWORD=$(kubectl get secret {{ include "cost-mgmt-infra.postgresql.secretName" . }} -n {{ .Release.Namespace }} -o jsonpath='{.data.password}' | base64 -d)

          # Set password for koku user
          echo "Setting password for database user: $KOKU_DB_USER..."
          kubectl exec postgres-0 -n {{ .Release.Namespace }} -- \
            psql -U postgres -d postgres -c "ALTER USER $KOKU_DB_USER WITH PASSWORD '$KOKU_DB_PASSWORD';"

          # Create pg_stat_statements extension
          echo "Creating pg_stat_statements extension on database: $KOKU_DB_NAME..."
          kubectl exec postgres-0 -n {{ .Release.Namespace }} -- \
            psql -U postgres -d "$KOKU_DB_NAME" -c "CREATE EXTENSION IF NOT EXISTS pg_stat_statements;" || true

          # Create hive role
          echo "Creating hive role..."
          ROLE_EXISTS=$(kubectl exec postgres-0 -n {{ .Release.Namespace }} -- \
            psql -U postgres -d postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='hive';" | tr -d '[:space:]')

          if [ "$ROLE_EXISTS" = "1" ]; then
            echo "Hive role already exists"
          else
            kubectl exec postgres-0 -n {{ .Release.Namespace }} -- \
              psql -U postgres -d postgres -c "CREATE ROLE hive WITH LOGIN;" || echo "Hive role may already exist"
          fi

          # Create hive database
          echo "Creating hive database..."
          DB_EXISTS=$(kubectl exec postgres-0 -n {{ .Release.Namespace }} -- \
            psql -U postgres -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='hive';" | tr -d '[:space:]')

          if [ "$DB_EXISTS" = "1" ]; then
            echo "Hive database already exists"
          else
            kubectl exec postgres-0 -n {{ .Release.Namespace }} -- \
              psql -U postgres -d postgres -c "CREATE DATABASE hive OWNER hive;" || echo "Hive database may already exist"
          fi

          echo "✅ Database initialization completed"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

