apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cost-mgmt-infra.fullname" . }}-db-init
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-mgmt-infra.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cost-mgmt-infra.fullname" . }}-db-init
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-mgmt-infra.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cost-mgmt-infra.fullname" . }}-db-init
subjects:
- kind: ServiceAccount
  name: {{ include "cost-mgmt-infra.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}

