{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-mgmt-infra.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  serviceName: {{ include "cost-mgmt-infra.postgresql.serviceName" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "cost-mgmt-infra.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgresql
  template:
    metadata:
      labels:
        {{- include "cost-mgmt-infra.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgresql
    spec:
      serviceAccountName: {{ include "cost-mgmt-infra.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.postgresql.securityContext | nindent 8 }}
      containers:
      - name: postgresql
        image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
        imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.postgresql.containerSecurityContext | nindent 10 }}
        ports:
        - name: postgresql
          containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ include "cost-mgmt-infra.postgresql.secretName" . }}
              key: database
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "cost-mgmt-infra.postgresql.secretName" . }}
              key: username
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "cost-mgmt-infra.postgresql.secretName" . }}
              key: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U $POSTGRESQL_USER
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U $POSTGRESQL_USER
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          {{- toYaml .Values.postgresql.resources | nindent 10 }}
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
  {{- if .Values.postgresql.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: postgresql-data
      labels:
        {{- include "cost-mgmt-infra.selectorLabels" . | nindent 8 }}
    spec:
      accessModes:
        {{- toYaml .Values.postgresql.persistence.accessModes | nindent 8 }}
      {{- if .Values.postgresql.persistence.storageClassName }}
      storageClassName: {{ .Values.postgresql.persistence.storageClassName }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.postgresql.persistence.size }}
  {{- else }}
  volumes:
  - name: postgresql-data
    emptyDir: {}
  {{- end }}
{{- end }}
