{{- if eq (include "cost-mgmt-infra.isOpenShift" .) "true" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-mgmt-infra.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: postgresql
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow connections from Cost Management application pods
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
          podSelector:
            matchLabels:
              app.kubernetes.io/part-of: cost-management-onprem
      ports:
        - protocol: TCP
          port: 5432
    # Allow connections from Cost Management infrastructure (Trino, Hive Metastore, etc.)
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
          podSelector:
            matchLabels:
              app.kubernetes.io/part-of: cost-management-infrastructure
      ports:
        - protocol: TCP
          port: 5432
    # Allow connections from migration job
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
          podSelector:
            matchLabels:
              app.kubernetes.io/component: migration
      ports:
        - protocol: TCP
          port: 5432
    # Allow connections from db-init job (uses kubectl exec, no direct connection)
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
          podSelector:
            matchLabels:
              app.kubernetes.io/component: db-init
      ports:
        - protocol: TCP
          port: 5432
  egress:
    # Allow DNS resolution
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-dns
      ports:
        - protocol: UDP
          port: 53
{{- end }}

