{{- if eq (include "cost-mgmt.jwt.shouldEnable" .) "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cost-mgmt.fullname" . }}-authorino
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-mgmt.labels" . | nindent 4 }}
    app.kubernetes.io/component: authorino
    app.kubernetes.io/part-of: ros-ocp
{{- end }}

