{{- if eq (include "ros-ocp.jwt.shouldEnable" .) "true" }}
---
# Role to allow Authorino to manage AuthConfigs and Secrets in its namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ros-ocp.fullname" . }}-authorino
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ros-ocp.labels" . | nindent 4 }}
    app.kubernetes.io/component: authorino-rbac
rules:
- apiGroups: ["authorino.kuadrant.io"]
  resources: ["authconfigs", "authconfigs/status"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ros-ocp.fullname" . }}-authorino
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ros-ocp.labels" . | nindent 4 }}
    app.kubernetes.io/component: authorino-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ros-ocp.fullname" . }}-authorino
subjects:
- kind: ServiceAccount
  name: {{ include "ros-ocp.fullname" . }}-authorino
  namespace: {{ .Release.Namespace }}
{{- end }}

