apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "cost-onprem.fullname" . }}-database
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-onprem.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
    app.kubernetes.io/name: database
spec:
  serviceName: {{ include "cost-onprem.fullname" . }}-database
  replicas: 1
  selector:
    matchLabels:
      {{- include "cost-onprem.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: database
      app.kubernetes.io/name: database
  template:
    metadata:
      labels:
        {{- include "cost-onprem.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: database
        app.kubernetes.io/name: database
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: postgres
          image: "{{ .Values.database.server.image.repository }}:{{ .Values.database.server.image.tag }}"
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          ports:
            - name: postgres
              containerPort: {{ .Values.database.server.port }}
              protocol: TCP
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "cost-onprem.database.defaultSecretName" . }}
                  key: admin-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "cost-onprem.database.defaultSecretName" . }}
                  key: admin-password
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U "$POSTGRES_USER"
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.failureThreshold }}
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U "$POSTGRES_USER"
            initialDelaySeconds: 5
            periodSeconds: {{ .Values.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.failureThreshold }}
          resources:
            {{- toYaml .Values.resources.database | nindent 12 }}
      volumes:
        - name: init-scripts
          configMap:
            name: {{ include "cost-onprem.fullname" . }}-db-init
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        volumeMode: {{ include "cost-onprem.storage.volumeMode" . }}
        storageClassName: {{ include "cost-onprem.storage.databaseClass" . }}
        resources:
          requests:
            storage: {{ .Values.database.server.storage.size }}
