apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cost-onprem.fullname" . }}-db-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-onprem.labels" . | nindent 4 }}
type: Opaque
data:
  ros-password: {{ .Values.database.ros.password | b64enc }}
  kruize-password: {{ .Values.database.kruize.password | b64enc }}
  sources-password: {{ .Values.database.sources.password | b64enc }}