apiVersion: v1
kind: Service
metadata:
  name: {{ include "cost-mgmt.fullname" . }}-db-ros
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-mgmt.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
    app.kubernetes.io/name: db-ros
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.database.ros.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "cost-mgmt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
    app.kubernetes.io/name: db-ros