apiVersion: v1
kind: Service
metadata:
  name: {{ include "cost-onprem.fullname" . }}-database
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-onprem.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
  annotations:
    # Deploy database service before migrations run (pre-install hook)
    # No delete policy - service persists and remains managed by Helm
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.database.server.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "cost-onprem.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
