apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cost-mgmt.koku.api.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-mgmt.koku.labels" . | nindent 4 }}
    app.kubernetes.io/component: cost-management-api
spec:
  selector:
    matchLabels:
      {{- include "cost-mgmt.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: cost-management-api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s

