apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cost-mgmt.trino.metastore.database.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-mgmt.trino.labels" . | nindent 4 }}
    app.kubernetes.io/component: hive-metastore-db
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "cost-mgmt.trino.metastore.database.secretName" .)) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $password := (get $secretData "password") | default (randAlphaNum 16 | b64enc) }}
  password: {{ $password | quote }}
  username: {{ .Values.trino.metastore.database.user | b64enc | quote }}
  database: {{ .Values.trino.metastore.database.name | b64enc | quote }}

