{{- if and .Values.ui (eq (include "cost-onprem.platform.isOpenShift" .) "true") }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "cost-onprem.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-onprem.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  {{- with (index .Values.serviceRoute.hosts 0) }}
  {{- if .host }}
  host: {{ .host | quote }}
  {{- end }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "cost-onprem.fullname" . }}-ui
  port:
    targetPort: https
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
{{- end }}

