{{- if and .Values.ui (eq (include "cost-onprem.platform.isOpenShift" .) "true") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cost-onprem.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-onprem.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
{{- end }}

