---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: insights-ros-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-mgmt.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingress
