---
# Secret for LDAP Service Account Credentials
# NOTE: Update these values with your enterprise LDAP settings
apiVersion: v1
kind: Secret
metadata:
  name: ldap-sync-credentials
  namespace: keycloak
  labels:
    app: ldap-sync
    component: credentials
type: Opaque
stringData:
  # LDAP Connection
  LDAP_HOST: "ldap://ldap.company.com:389"
  LDAP_BIND_DN: "CN=svc-keycloak-sync,OU=ServiceAccounts,DC=company,DC=com"
  LDAP_BIND_PASSWORD: "CHANGE_ME"  # Service account password
  LDAP_BASE_DN: "DC=company,DC=com"

  # LDAP Structure
  LDAP_USER_BASE: "OU=Users,DC=company,DC=com"
  LDAP_GROUP_BASE: "OU=CostMgmt,OU=Groups,DC=company,DC=com"

  # Attribute Mapping
  # These should match the attributes in your LDAP that contain org_id and account_number
  ORG_ID_ATTR: "costCenter"      # LDAP attribute for organization ID
  ACCOUNT_ATTR: "division"       # LDAP attribute for account number

  # Group Naming (with namespace prefix to avoid collisions)
  ORG_GROUP_PREFIX: "cost-mgmt-org-"
  ACCOUNT_GROUP_PREFIX: "cost-mgmt-account-"

  # Logging
  LOG_LEVEL: "INFO"  # DEBUG, INFO, WARN, ERROR

---
# ConfigMap for Sync Script
apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-sync-script
  namespace: keycloak
  labels:
    app: ldap-sync
    component: script
data:
  sync.sh: |
    #!/bin/bash
    # This ConfigMap should contain the full sync script
    # Copy the contents from scripts/ldap-user-attrs-to-groups-sync.sh
    #
    # OR mount the script from a volume if you have it in a repository

    echo "ERROR: Script not configured!"
    echo "Please update this ConfigMap with the sync script from:"
    echo "  scripts/ldap-user-attrs-to-groups-sync.sh"
    exit 1

---
# CronJob to Run Sync Daily
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ldap-user-attrs-sync
  namespace: keycloak
  labels:
    app: ldap-sync
    component: cronjob
spec:
  # Run daily at 2 AM
  schedule: "0 2 * * *"

  # Keep last 3 successful and 3 failed jobs for debugging
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3

  # Don't allow concurrent runs (prevent conflicts)
  concurrencyPolicy: Forbid

  # Start new job if scheduled time is missed by less than 100 seconds
  startingDeadlineSeconds: 100

  jobTemplate:
    metadata:
      labels:
        app: ldap-sync
        component: job
    spec:
      # Retry once if job fails
      backoffLimit: 1

      # Job timeout: 30 minutes
      activeDeadlineSeconds: 1800

      template:
        metadata:
          labels:
            app: ldap-sync
            component: pod
        spec:
          restartPolicy: OnFailure

          # Use service account with LDAP network access
          serviceAccountName: default

          containers:
          - name: ldap-sync
            # Use alpine with ldap-utils
            image: alpine:3.18

            command:
            - /bin/sh
            - -c
            - |
              # Install ldap-utils
              apk add --no-cache openldap-clients bash

              # Run sync script
              chmod +x /scripts/sync.sh
              /scripts/sync.sh

            # Load environment from secret
            envFrom:
            - secretRef:
                name: ldap-sync-credentials

            # Mount sync script
            volumeMounts:
            - name: script
              mountPath: /scripts
              readOnly: true

            # Resource limits
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 256Mi

            # Security context
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              runAsUser: 1000
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: false  # Need to install packages

          volumes:
          - name: script
            configMap:
              name: ldap-sync-script
              defaultMode: 0755

---
# Optional: NetworkPolicy to allow egress to LDAP server
# Uncomment and adjust if your cluster uses NetworkPolicies
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: ldap-sync-egress
#   namespace: keycloak
# spec:
#   podSelector:
#     matchLabels:
#       app: ldap-sync
#   policyTypes:
#   - Egress
#   egress:
#   - to:
#     - podSelector: {}  # Allow DNS
#     ports:
#     - protocol: UDP
#       port: 53
#   - to:
#     - ipBlock:
#         cidr: 10.0.0.0/8  # Adjust to your LDAP server IP range
#     ports:
#     - protocol: TCP
#       port: 389  # LDAP
#     - protocol: TCP
#       port: 636  # LDAPS

