{{- if eq (include "cost-mgmt.jwt.shouldEnable" .) "true" }}
---
# ClusterRole to allow Authorino to perform TokenReview for validating Kubernetes tokens
# This permission is granted to the Authorino service account deployed by this Helm chart
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cost-mgmt.fullname" . }}-authorino-tokenreview
  labels:
    {{- include "cost-mgmt.labels" . | nindent 4 }}
    app.kubernetes.io/component: authorino-rbac
rules:
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cost-mgmt.fullname" . }}-authorino-tokenreview
  labels:
    {{- include "cost-mgmt.labels" . | nindent 4 }}
    app.kubernetes.io/component: authorino-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cost-mgmt.fullname" . }}-authorino-tokenreview
subjects:
- kind: ServiceAccount
  name: {{ include "cost-mgmt.fullname" . }}-authorino
  namespace: {{ .Release.Namespace }}
{{- end }}

