{{- $sourceSecret := lookup "v1" "Secret" .Values.infrastructure.storage.credentialsSecret.namespace .Values.infrastructure.storage.credentialsSecret.name -}}
{{- if $sourceSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cost-mgmt.storage.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-mgmt.labels" . | nindent 4 }}
type: Opaque
data:
  access-key: {{ index $sourceSecret.data .Values.infrastructure.storage.credentialsSecret.accessKeyKey }}
  secret-key: {{ index $sourceSecret.data .Values.infrastructure.storage.credentialsSecret.secretKeyKey }}
{{- else }}
{{- fail (printf "Source secret %s/%s not found. Please ensure ODF/NooBaa is deployed or provide valid S3 credentials." .Values.infrastructure.storage.credentialsSecret.namespace .Values.infrastructure.storage.credentialsSecret.name) }}
{{- end }}

