apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cost-mgmt.koku.django.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-mgmt.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ randAlphaNum 64 | b64enc | quote }}

