{{- if .Values.sourcesApi.enabled }}
{{- $sourcesCredsSecretName := printf "%s-sources-credentials" (include "cost-management-onprem.fullname" .) -}}
{{- $sourcesCredsSecret := lookup "v1" "Secret" .Release.Namespace $sourcesCredsSecretName -}}
{{- $dbPassword := "" -}}
{{- if $sourcesCredsSecret -}}
  {{- $dbPassword = index $sourcesCredsSecret.data "database-password" -}}
{{- else -}}
  {{- $dbPassword = randAlphaNum 32 | b64enc -}}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cost-management-onprem.fullname" . }}-sources-db-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-management-onprem.labels" . | nindent 4 }}
    app.kubernetes.io/component: sources-api
type: Opaque
data:
  # This MUST match the database-password in koku-sources-credentials
  # Using lookup to ensure they're synchronized
  sources-password: {{ $dbPassword | quote }}
{{- end }}

