{{- if .Values.sourcesApi.enabled }}
{{- $secretName := printf "%s-sources-credentials" (include "cost-management-onprem.fullname" .) -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- $dbPassword := "" -}}
{{- $encryptionKey := "" -}}
{{- if $existingSecret -}}
  {{- $dbPassword = index $existingSecret.data "database-password" -}}
  {{- $encryptionKey = index $existingSecret.data "encryption-key" -}}
{{- else -}}
  {{- $dbPassword = randAlphaNum 32 | b64enc -}}
  {{- $encryptionKey = randAlphaNum 64 | b64enc -}}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-management-onprem.labels" . | nindent 4 }}
    app.kubernetes.io/component: sources-api
type: Opaque
data:
  database-password: {{ $dbPassword | quote }}
  encryption-key: {{ $encryptionKey | quote }}
{{- end }}

