apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cost-mgmt.koku.django.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-mgmt.koku.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "cost-mgmt.koku.django.secretName" .)) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $secretKey := (get $secretData "secret-key") | default (randAlphaNum (int .Values.costManagement.django.secretKeyLength) | b64enc) }}
  secret-key: {{ $secretKey | quote }}

