{{- /* Skip bucket creation job if using external ObjectBucketClaim */ -}}
{{- if not .Values.odf.useExternalOBC }}
{{- $isOpenShift := eq (include "cost-onprem.platform.isOpenShift" .) "true" }}
{{- $storageEndpoint := include "cost-onprem.storage.endpoint" . }}
{{- $storagePort := include "cost-onprem.storage.port" . }}
{{- $useSSL := eq (include "cost-onprem.storage.useSSL" .) "true" }}
{{- $protocol := ternary "https" "http" $useSSL }}
{{- /* MinIO endpoint already includes port, ODF does not */ -}}
{{- $s3Url := "" }}
{{- if $isOpenShift }}
{{- $s3Url = printf "%s://%s:%s" $protocol $storageEndpoint $storagePort }}
{{- else }}
{{- $s3Url = printf "%s://%s" $protocol $storageEndpoint }}
{{- end }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cost-onprem.fullname" . }}-s3-buckets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-onprem.labels" . | nindent 4 }}
    app.kubernetes.io/component: setup
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "cost-onprem.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: setup
    spec:
      restartPolicy: OnFailure
      securityContext:
        {{- if $isOpenShift }}
        {{- include "cost-onprem.securityContext.pod.nonRoot" . | nindent 8 }}
        {{- else }}
        runAsNonRoot: false
        {{- end }}
      initContainers:
        - name: wait-for-s3
          image: "{{ .Values.global.initContainers.waitFor.repository }}:{{ .Values.global.initContainers.waitFor.tag }}"
          securityContext:
            {{- include "cost-onprem.securityContext.nonRoot" . | nindent 12 }}
          command: ['bash', '-c']
          args:
            {{- if $isOpenShift }}
            - |
              echo "Waiting for S3 storage at {{ $storageEndpoint }}:{{ $storagePort }}..."
              until timeout 3 bash -c "echo > /dev/tcp/{{ $storageEndpoint }}/{{ $storagePort }}" 2>/dev/null; do
                echo "S3 storage not ready yet, retrying in 5 seconds..."
                sleep 5
              done
              echo "S3 storage is ready"
            {{- else }}
            - |
              echo "Waiting for MinIO at {{ include "cost-onprem.fullname" . }}-minio:{{ .Values.minio.ports.api }}..."
              until timeout 3 bash -c "echo > /dev/tcp/{{ include "cost-onprem.fullname" . }}-minio/{{ .Values.minio.ports.api }}" 2>/dev/null; do
                echo "MinIO not ready yet, retrying in 5 seconds..."
                sleep 5
              done
              echo "MinIO is ready"
            {{- end }}
      containers:
        - name: create-buckets
          image: "{{ .Values.global.initContainers.minioMc.repository }}:{{ .Values.global.initContainers.minioMc.tag }}"
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            {{- if not $isOpenShift }}
            runAsUser: 1001
            {{- end }}
            {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
            seccompProfile:
              type: RuntimeDefault
            {{- end }}
          volumeMounts:
            - name: mc-config
              mountPath: /.mc
          env:
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "cost-onprem.fullname" . }}-storage-credentials
                  key: access-key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "cost-onprem.fullname" . }}-storage-credentials
                  key: secret-key
            - name: S3_URL
              value: "{{ $s3Url }}"
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Configuring S3 storage at ${S3_URL}..."

              # Set up mc alias with appropriate SSL handling
              {{- if $useSSL }}
              # TODO: Remove --insecure flag in production environments with proper certificates.
              # Using --insecure for self-signed certificates (common in ODF/OpenShift dev environments)
              MC_INSECURE="--insecure"
              {{- else }}
              MC_INSECURE=""
              {{- end }}

              # Wait for S3 to be ready and set alias
              for i in $(seq 1 10); do
                if /usr/bin/mc ${MC_INSECURE} alias set s3storage ${S3_URL} ${S3_ACCESS_KEY} ${S3_SECRET_KEY} >/dev/null 2>&1; then
                  echo "S3 storage is ready!"
                  break
                else
                  echo "S3 storage not ready, waiting... (attempt $i/10)"
                  sleep 3
                fi
              done

              # Final alias setup (fail if not working)
              /usr/bin/mc ${MC_INSECURE} alias set s3storage ${S3_URL} ${S3_ACCESS_KEY} ${S3_SECRET_KEY} || exit 1

              # Create buckets
              {{- range .Values.minio.buckets }}
              echo "Creating bucket: {{ . }}"
              /usr/bin/mc ${MC_INSECURE} mb --ignore-existing s3storage/{{ . }}
              {{- if not $isOpenShift }}
              # Set public access for MinIO (not needed for ODF which uses IAM policies)
              /usr/bin/mc ${MC_INSECURE} anonymous set public s3storage/{{ . }}
              {{- end }}
              {{- end }}

              echo "S3 bucket setup completed successfully"
              /usr/bin/mc ${MC_INSECURE} ls s3storage/
      volumes:
        - name: mc-config
          emptyDir: {}
{{- end }}