{{- $secretName := include "cost-onprem.storage.secretName" . -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}

{{- if not $existingSecret -}}
{{/*
Storage credentials secret - PLACEHOLDER ONLY

⚠️  WARNING: This secret should be created by scripts/install-helm-chart.sh
    before Helm deployment. This template only generates placeholder values
    to allow "helm template" validation.

Real deployments:
  - Secrets created by install-helm-chart.sh with secure random passwords
  - For ODF: Auto-discovers credentials from openshift-storage/noobaa-admin
  - For MinIO: Generates random credentials (minioadmin / random-32-char)

If you see this secret in a real deployment, the install script was skipped!
*/}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-onprem.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
  annotations:
    cost-onprem.io/credential-source: "PLACEHOLDER - Create via install-helm-chart.sh"
    "helm.sh/resource-policy": keep
type: Opaque
data:
  # Base64 encoded placeholder values for "helm template" validation only
  # Real deployments: Created by scripts/install-helm-chart.sh
  access-key: {{ "PLACEHOLDER_ACCESS_KEY" | b64enc }}
  secret-key: {{ "PLACEHOLDER_SECRET_KEY" | b64enc }}

{{- end -}}
