{{- $secretName := include "cost-onprem.storage.secretName" . -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}

{{- if not $existingSecret -}}
{{/*
Storage credentials secret creation
Supports: ODF (production) and MinIO standalone (CI)
*/}}

{{- $accessKey := "" -}}
{{- $secretKey := "" -}}
{{- $credSource := "none" -}}
{{- $isDryRun := false -}}
{{- $noobaaList := dict -}}{{/* Initialize to empty dict so it's available for error handling */}}

{{/* 0. Check for explicit credentials first (avoids all lookups) */}}
{{- if and .Values.odf .Values.odf.credentials -}}
  {{- if and .Values.odf.credentials.accessKey .Values.odf.credentials.secretKey -}}
    {{- /* Credentials explicitly provided via values */ -}}
    {{- $accessKey = .Values.odf.credentials.accessKey | b64enc -}}
    {{- $secretKey = .Values.odf.credentials.secretKey | b64enc -}}
    {{- $credSource = "explicit-values" -}}
  {{- end -}}
{{- end -}}

{{/* Only do lookups if credentials weren't explicitly provided */}}
{{- if eq $accessKey "" -}}
{{/* Detect dry-run mode: lookup for v1/Secret returns nil when no cluster connection */}}
{{- $testLookup := lookup "v1" "Secret" "" "" -}}
{{- if not $testLookup -}}
  {{- $isDryRun = true -}}
{{- end -}}

{{/* 1. Check for ODF NooBaa CRD */}}
{{- $noobaaList = lookup "noobaa.io/v1alpha1" "NooBaa" "" "" -}}
{{- if and $noobaaList $noobaaList.items (gt (len $noobaaList.items) 0) -}}
  {{- /* ODF detected - get credentials from noobaa-admin secret */ -}}
  {{- $noobaaSecret := lookup "v1" "Secret" "openshift-storage" "noobaa-admin" -}}
  {{- if $noobaaSecret -}}
    {{- if and (index $noobaaSecret.data "AWS_ACCESS_KEY_ID") (index $noobaaSecret.data "AWS_SECRET_ACCESS_KEY") -}}
      {{- $accessKey = index $noobaaSecret.data "AWS_ACCESS_KEY_ID" -}}
      {{- $secretKey = index $noobaaSecret.data "AWS_SECRET_ACCESS_KEY" -}}
      {{- $credSource = "openshift-storage/noobaa-admin (ODF)" -}}
    {{- end -}}
  {{- end -}}
{{- else -}}
  {{- /* MinIO standalone (CI pattern) - look for cost-onprem-odf-credentials */ -}}
  {{- $ciCredentials := lookup "v1" "Secret" .Release.Namespace "cost-onprem-odf-credentials" -}}
  {{- if $ciCredentials -}}
    {{- if and (index $ciCredentials.data "access-key") (index $ciCredentials.data "secret-key") -}}
      {{- $accessKey = index $ciCredentials.data "access-key" -}}
      {{- $secretKey = index $ciCredentials.data "secret-key" -}}
      {{- $credSource = printf "%s/cost-onprem-odf-credentials (CI)" .Release.Namespace -}}
    {{- end -}}
  {{- end -}}

  {{- /* Fallback: Check minio namespace */ -}}
  {{- if eq $accessKey "" -}}
    {{- $minioCredentials := lookup "v1" "Secret" "minio" "minio-credentials" -}}
    {{- if $minioCredentials -}}
      {{- if and (index $minioCredentials.data "access-key") (index $minioCredentials.data "secret-key") -}}
        {{- $accessKey = index $minioCredentials.data "access-key" -}}
        {{- $secretKey = index $minioCredentials.data "secret-key" -}}
        {{- $credSource = "minio/minio-credentials (standalone)" -}}
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
{{- end -}}{{/* End of: if eq $accessKey "" (skip lookups if explicit credentials provided) */}}

{{/* 2. Handle missing credentials */}}
{{- if eq $accessKey "" -}}
  {{- if $isDryRun -}}
    {{- /* Dry-run mode: create placeholder secret for validation */ -}}
    {{- $accessKey = "ZHJ5LXJ1bi1wbGFjZWhvbGRlcg==" -}}
    {{- $secretKey = "ZHJ5LXJ1bi1wbGFjZWhvbGRlcg==" -}}
    {{- $credSource = "dry-run-placeholder" -}}
  {{- else -}}
    {{- /* Real deployment: fail with helpful error */ -}}
    {{- $noobaaDetected := and $noobaaList $noobaaList.items (gt (len $noobaaList.items) 0) -}}
    {{- if $noobaaDetected -}}
      {{- fail "ODF detected but credentials not found.\n\nExpected secret: openshift-storage/noobaa-admin\n\nPlease ensure OpenShift Data Foundation is properly installed with NooBaa." -}}
    {{- else -}}
      {{- fail (printf "MinIO credentials not found.\n\nExpected one of:\n  - %s/cost-onprem-odf-credentials (CI standard)\n  - minio/minio-credentials (standalone)\n\nPlease create credentials:\n  kubectl create secret generic cost-onprem-odf-credentials \\\n    --namespace=%s \\\n    --from-literal=access-key=<access-key> \\\n    --from-literal=secret-key=<secret-key>" .Release.Namespace .Release.Namespace) -}}
    {{- end -}}
  {{- end -}}
{{- end -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-onprem.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
  annotations:
    cost-onprem.io/credential-source: {{ $credSource | quote }}
    "helm.sh/resource-policy": keep
type: Opaque
data:
  access-key: {{ $accessKey }}
  secret-key: {{ $secretKey }}

{{- end -}}
