{{/*
Storage credentials secret - PLACEHOLDER ONLY

This template is skipped when objectStorage.existingSecret is set (user provides their own secret).
Otherwise, it creates a placeholder secret to allow "helm template" validation.

Real deployments should have credentials created by one of:
  1. The user (pre-create the secret and set objectStorage.existingSecret in values.yaml)
  2. scripts/install-helm-chart.sh (auto-creates before helm install)
*/}}
{{- if eq (include "cost-onprem.storage.hasExistingSecret" .) "false" -}}
{{- $secretName := include "cost-onprem.storage.secretName" . -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-onprem.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
  annotations:
    cost-onprem.io/credential-source: "PLACEHOLDER - Create via install-helm-chart.sh or set objectStorage.existingSecret"
    "helm.sh/resource-policy": keep
type: Opaque
data:
  # Base64 encoded placeholder values for "helm template" validation only
  # Real deployments: Created by install-helm-chart.sh or user-managed
  access-key: {{ "PLACEHOLDER_ACCESS_KEY" | b64enc }}
  secret-key: {{ "PLACEHOLDER_SECRET_KEY" | b64enc }}
{{- end -}}
