{{- $isOpenShift := eq (include "cost-onprem.platform.isOpenShift" .) "true" }}
{{- if not $isOpenShift }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cost-onprem.fullname" . }}-minio
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-onprem.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
    app.kubernetes.io/name: minio
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.minio.ports.api }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.minio.ports.console }}
      targetPort: console
      protocol: TCP
      name: console
  selector:
    {{- include "cost-onprem.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: storage
    app.kubernetes.io/name: minio
{{- end }}